/* take the command table generated by the parser
for every SimpleCommand in the array it creates a new process
create pipes to communicate the output
of one process to the input of the next one
redirect the stdin, stdout, and strderr if there are any redirections */