/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   executor.c                                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: sbars <sbars@student.42.fr>                +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/10/27 15:22:46 by sbars             #+#    #+#             */
/*   Updated: 2022/10/27 16:09:57 by sbars            ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "minishell.h"
/* take the command table generated by the parser
for every SimpleCommand in the array it creates a new process
create pipes to communicate the output
of one process to the input of the next one
redirect the stdin, stdout, and strderr if there are any redirections */

void	executor(t_meta *pkg)
{
	(void) pkg;
}
